global:
  scrape_interval: 10s  # Scrape targets every 10 seconds (meets RNF-06)
  evaluation_interval: 10s  # Evaluate rules every 10 seconds
  scrape_timeout: 5s  # Timeout for scrapes

# Alert manager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Rule files to load
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Scrape the requester application exposing metrics
  - job_name: 'azure-requester'
    static_configs:
      - targets: ['requester:8001']
    metrics_path: '/metrics'

  # Self-monitor Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']